# Generated by Django 2.2.16 on 2020-10-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sku', models.IntegerField(max_length=10)),
                ('client', models.CharField(max_length=110)),
                ('addTime', models.DateTimeField(auto_now=True)),
                ('totalCost', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('brand', models.CharField(max_length=110)),
                ('lastPrice', models.PositiveIntegerField()),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('lastChangeTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactorLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factors.Factor')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factors.Item')),
            ],
        ),
    ]
