# Generated by Django 2.2.16 on 2020-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
