# Generated by Django 2.2.12 on 2020-10-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0002_auto_20201022_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorlookup',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factorlookup',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
