# Generated by Django 2.2.16 on 2020-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factors', '0003_auto_20201023_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='sku',
            field=models.IntegerField(unique=True),
        ),
    ]
